version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
  backend:
    container_name: spring-boot-project
    image: spring-boot-project
    build: backend/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
  frontend:
    container_name: angular-project
    image: angular-project
    build: frontend/.
    ports:
    - "4200:4200"
    depends_on:
      - backend
